### ISSUE TITLE
ListOffsets returns earliest offset locally, not taking remote into account

### ISSUE THREAD

**Issue by ivanyu** [aiven/kafka#14]
Assuming the beginning of the log is on remote
```
kcat -b localhost:9092 -C -t topic1 -o beginning -e -f "%o\n" | head
```
fetches only the locally available records, but
```
kcat -b localhost:9092 -C -t topic1 -o 0 -e -f "%o\n" | head
```
fetches records from the remote storage.

This Python
```python
tp = TopicPartition("topic1", 0)
kc.assign([tp])
kc.seek_to_beginning(tp)
r = kc.poll(timeout_ms=1)
```
fetches from the remote.

The issue is that when we request the earliest offset from the broker (`ListOffsets` request type / `beginning_offsets` in Python)), it returns the earliest available locally, i.e. not counting remote.

**Comment by mdedetrich** [comment]
So I have created an implementation locally, wasn't too hard but I need to verify whether the returning offsets need to be ordered in some way.

**Comment by mdedetrich** [comment]
Here is the patch so far, going to confirm how ordering is meant to work.

[Make_ListOffsets_work_with_Tiered_Storage.patch](https://github.com/aiven/kafka/files/11541997/Make_ListOffsets_work_with_Tiered_Storage.patch)

**Comment by HenryCaiHaiying** [comment]
Are we moving forward with the patching?  It seems it might be important for some consumers.

**Comment by ivanyu** [comment]
@mdedetrich did the patch work for you? It doesn't for me, the `kcat` test.

At least `log.logStartOffset` as a parameter to `findOffsetByTimestamp` will not produce anything, because `log.logStartOffset` is always (currently) higher than anything in the remote storage.

Also, based on how `oldStyleOffsets` is used later, it should always be 0 or 1 element, so I guess `++` won't work.

**Comment by mdedetrich** [comment]
Indeed this is correct, I was trying to write a test to validate this and I noticed the same. I was attempting to upstream this first and the core implementation of `ListOffsets` has changed compared to whats in 3.3.
